/*
 * Ambient types for the build-time virtual module `virtual:doc-kitty/manifest`
 * (generated by the Astro integration in `src/lib/manifest.ts`; ADR-0013/0015).
 *
 * WP03 types ONLY the `slotComponents` export — the per-carrier `dk:` slot lookup
 * the four carriers read to render a theme override when present. This lets the
 * carriers import the binding cleanly, without scattering `@ts-expect-error`
 * across each `.astro` file.
 *
 * `resolveLayout` is deliberately NOT re-declared here. The single layout seam
 * (`src/layouts/kind-layouts.ts`, WP02) already imports `resolveLayout` under a
 * `@ts-expect-error`, and that file is outside WP03's owned surface. Leaving
 * `resolveLayout` undeclared keeps the module's `resolveLayout` member absent, so
 * WP02's existing suppression at the layout seam stays valid (an unused
 * `@ts-expect-error` would itself be a type error).
 */
declare module 'virtual:doc-kitty/manifest' {
  export const slotComponents: import('./lib/manifest.js').SlotComponents;
}
