/*
 * Ambient types for the build-time virtual module `virtual:doc-kitty/manifest`
 * (generated by the Astro integration in `src/lib/manifest.ts`; ADR-0013/0015).
 *
 * WP03 types the `slotComponents` export — the per-carrier `dk:` slot lookup
 * the four carriers read to render a theme override when present — and (M2 F2 fix)
 * `themeSocialImage`, the statically-imported theme `assets.socialImage` the Head
 * carrier forwards to HeadShare as the terminal site-default share image. This lets
 * the carriers import the bindings cleanly, without scattering `@ts-expect-error`
 * across each `.astro` file.
 *
 * `resolveLayout` is deliberately NOT re-declared here. The single layout seam
 * (`src/layouts/kind-layouts.ts`, WP02) already imports `resolveLayout` under a
 * `@ts-expect-error`, and that file is outside WP03's owned surface. Leaving
 * `resolveLayout` undeclared keeps the module's `resolveLayout` member absent, so
 * WP02's existing suppression at the layout seam stays valid (an unused
 * `@ts-expect-error` would itself be a type error).
 */
declare module 'virtual:doc-kitty/manifest' {
  export const slotComponents: import('./lib/manifest.js').SlotComponents;
  /**
   * The theme's `assets.socialImage`, statically imported so it rides Astro's
   * asset pipeline (hashed, servable URL). `undefined` when the theme sets none,
   * so the toolkit-shipped default remains the terminal fallback. Typed as
   * `ImageMetadata` for the fields HeadShare reads (`src`/`format`); an SVG import
   * resolves at runtime to a component with those metadata fields assigned.
   */
  export const themeSocialImage: import('astro').ImageMetadata | undefined;
}
