/**
 * `kind → layout` resolution — the SINGLE import site (ADR-0013 seam 1).
 *
 * Resolved at one place only: the `MarkdownContent` carrier reads
 * `entry.data.kind` and wraps the content in `resolveLayout(kind)`.
 *
 * M2 swap (ADR-0015 decision 1): this module no longer owns a static `kind →
 * layout` map. It now DELEGATES to the merged virtual manifest
 * (`virtual:doc-kitty/manifest`, generated by the Astro integration in
 * `src/lib/manifest.ts` from the resolved theme). The `resolveLayout` signature
 * is UNCHANGED — synchronous `(kind: string | undefined) => LayoutComponent` with
 * a `Default` fallback — so the layout-resolution call site in
 * `MarkdownContent.astro` is unchanged from M1.
 *
 * No-theme parity: with no theme the manifest equals the M1 static module — `Hub`
 * registered, every other kind → `Default` — so the Hub pages still render their
 * bespoke in-frame layout and unknown/absent kinds still fall back (never throw;
 * the standalone validator only warns on unknown kinds — ADR-0009).
 */
import type { LayoutComponent, ResolveLayout } from '../lib/manifest.js';

// The manifest is a build-time virtual module (generated by the Astro
// integration in `src/lib/manifest.ts`); it has no static `.d.ts` home in the
// toolkit sources, so `astro check` cannot resolve its types. Import the runtime
// binding and re-export it under the manifest's published `ResolveLayout` type —
// preserving the exact M1 synchronous signature at this single seam.
// @ts-expect-error virtual:doc-kitty/manifest is resolved by Vite at build time.
import { resolveLayout as manifestResolveLayout } from 'virtual:doc-kitty/manifest';

export type { LayoutComponent };

/** Resolve the layout for a page `kind`; unknown/absent → `Default`. */
export const resolveLayout: ResolveLayout = manifestResolveLayout;
